### ISSUE TITLE
Maven Dependencies Version?

### ISSUE THREAD

**Issue by khoa-nd** [formentor-studio/magnolia-ai-contents-public#1]
Hi,

I have tried to search Maven Central Repo but cannot find this maven dependency specs. Could you tell me what Maven repo where this dependency currently is hosted?

Thanks

**Comment by joaquin-alfaro** [comment]
Hi @khoa-nd,

  We are working on it and we are planning to publish the modules in Maven Central on next week.
  Until then, we provide the project [magnolia-ai-contents-bundle](https://github.com/formentor-studio/magnolia-ai-contents-bundle) as a template for the generation of both modules and the integration in a bundle of Magnolia.

Sorry for the inconveniences

**Comment by joaquin-alfaro** [comment]
The module has been published in Maven Central, below is the maven dependency:

```
      <dependency>
        <groupId>com.formentor-studio.magnolia</groupId>
        <artifactId>magnolia-ai-contents</artifactId>
        <version>0.0.1</version>
      </dependency>
```

For more details here is the link to the artifact https://central.sonatype.com/artifact/com.formentor-studio.magnolia/magnolia-ai-contents
