### ISSUE TITLE
ai-training module inquiry

### ISSUE THREAD

**Issue by rdlfperezIII** [formentor-studio/magnolia-ai-contents-public#2]
Hello, is this already available in maven central?
```

<dependencies>
    <dependency>
        <groupId>org.formentor</groupId>
        <artifactId>ai-training</artifactId>
        <version>${ai-contents.version}</version>
    </dependency>
</dependencies>
```

**Comment by joaquin-alfaro** [comment]
Hi, currently it is just published in maven central [magnolia-ai-contents](https://github.com/formentor-studio/magnolia-ai-contents) but we are planning to publish **ai-training** soon

Sorry for the inconveniences.

**Comment by rdlfperezIII** [comment]
Thanks for the response @joaquin-alfaro , is there any workaround for this?

**Comment by joaquin-alfaro** [comment]
Not at this moment, but as soon as the artifact is available in Maven central we will add a comment.

**Comment by joaquin-alfaro** [comment]
Hi @rdlfperezIII, the artifact has been published in Maven Central, here you have the dependency:
```
<dependency>
  <groupId>com.formentor-studio.magnolia</groupId>
  <artifactId>magnolia-ai-training</artifactId>
  <version>0.0.1</version>
</dependency>
```
By the other hand, the source code of the module have been moved to https://github.com/formentor-studio/magnolia-ai-training in case you need check something.

If you have any question about the module do not hesitate to ask

**Comment by rdlfperezIII** [comment]
> Hi @rdlfperezIII, the artifact has been published in Maven Central, here you have the dependency:
> 
> ```
> <dependency>
>   <groupId>com.formentor-studio.magnolia</groupId>
>   <artifactId>magnolia-ai-training</artifactId>
>   <version>0.0.1</version>
> </dependency>
> ```
> 
> By the other hand, the source code of the module have been moved to https://github.com/formentor-studio/magnolia-ai-training in case you need check something.
> 
> If you have any question about the module do not hesitate to ask

Thank you!
